-- Migration 022: Tax Ledger Resolution + Client Accounting Policy Engine architecture decisions

INSERT INTO prompt_rules (key, description, content) VALUES

('logic:tax:ledger_mapping_is_lookup_not_resolution',
 'Tax ledger mapping is a deterministic lookup, not a resolution engine',
 'ARCHITECTURE DECISION: Tax ledger mapping is fundamentally simpler than supplier, item, and charge resolution. It is a deterministic lookup, not an identity or classification problem. Once three things are known — (1) GST rate from the invoice line item, (2) tax type (CGST+SGST or IGST, determined by comparing supplier state with buyer state), (3) client ledger structure (from uploaded ledger master) — the correct tax ledger is determined with no ambiguity and no human decision required. Call it a Tax Ledger Mapping Table, not a resolution engine. It is configured once per client (inferred from their ledger master upload) and applied automatically forever. The complexity is in setup, not in runtime resolution.'),

('logic:tax:supplier_determines_tax_type',
 'Supplier resolution determines tax type — supplier and tax resolution are linked',
 'ARCHITECTURE DECISION: When a supplier is resolved, their state is determined from their GSTIN (first two characters). Comparing supplier state with the buyer company state determines whether the invoice uses CGST+SGST (same state) or IGST (different states). This determination happens at supplier resolution time and flows directly into tax ledger mapping. Tax type cannot be determined until supplier is resolved. Correct sequence: (1) Resolve supplier → supplier state known. (2) Compare supplier state with buyer state → CGST+SGST or IGST determined. (3) Get GST rate from each line item. (4) Tax ledger lookup: rate + type → specific ledger from client mapping table. Supplier Resolution and Tax Resolution are therefore not independent modules.'),

('logic:tax:generic_vs_ratewise_ledgers',
 'Support both generic and rate-wise GST ledger structures — learn from client ledger master',
 'ARCHITECTURE DECISION: Two types of GST ledger structures exist. TYPE 1 — Generic (single ledger per tax type): Input CGST, Input SGST, Input IGST. All GST rates post to the same ledger. TYPE 2 — Rate-wise (separate ledger per rate): Input CGST 2.5%, Input CGST 6%, Input CGST 9%, Input IGST 5%, Input IGST 12%, etc. The system must NOT hardcode either structure. Instead it must analyse the client''s uploaded Ledger Master to detect which structure this client uses, then apply the correct mapping automatically. For TYPE 1: any GST rate maps to the same ledger. For TYPE 2: each GST rate maps to its corresponding rate-specific ledger. No popup required — the mapping is deterministic once the client structure is known.'),

('logic:tax:itc_eligibility_defer',
 'ITC eligibility treatment deferred — requires Client Accounting Policy configuration',
 'ARCHITECTURE DECISION: ITC eligibility varies significantly across clients and cannot be solved through invoice extraction alone. It is an accounting policy decision. TWO FUNDAMENTALLY DIFFERENT TREATMENTS EXIST: (1) ITC-claiming business: Inventory/Expense = ₹100, Input GST = ₹18. Two separate ledger entries. (2) Non-ITC business: Inventory/Expense = ₹118. Single entry, GST absorbed into cost. No GST ledger posting. The correct treatment must be driven by the Client Accounting Policy Engine questionnaire answer: "Does this client claim ITC?" This field is mandatory in the client onboarding questionnaire. Until the questionnaire is answered, the system cannot generate the correct Tally voucher for this client. ITC eligibility at line-item level (some items eligible, some blocked) is a further complexity to be addressed after the basic policy is established.'),

('logic:tax:section_17_5_blocked_credits',
 'Section 17(5) blocked ITC credits — system-level list, not client configuration',
 'ARCHITECTURE DECISION: Certain purchases have ITC permanently blocked by Indian GST law under Section 17(5), regardless of the client''s accounting policy. These include: food and beverages, outdoor catering, beauty treatments, health services, travel benefits to employees, club memberships, works contract services for immovable property construction, goods or services for personal consumption, and motor vehicles for personal use. These are NOT a client configuration choice — they are legal requirements. The system must maintain a built-in list of these blocked categories that overrides even a client policy that says "claim all ITC". When an invoice line item falls into a Section 17(5) category, ITC must be blocked automatically and the cost must be absorbed into the expense/inventory value regardless of client ITC policy.'),

('logic:tax:composition_scheme_suppliers',
 'Edge case: Composition Scheme suppliers — no GST charged, no ITC claimable',
 'ARCHITECTURE DECISION: Suppliers registered under the GST Composition Scheme cannot charge GST on their invoices. An invoice from a Composition Scheme supplier shows zero GST. However this is different from a zero-rated or exempt item — the reason matters for accounting. The buyer CANNOT claim any ITC on Composition Scheme purchases. The accounting entry is: full invoice value (including any implied tax) posted to the expense or purchase ledger, no Input GST entry at all. The system must detect Composition Scheme suppliers (identifiable from their GSTIN registration type) and handle the accounting entry accordingly. This must not be confused with zero-GST exempt items.'),

('logic:tax:reverse_charge_mechanism',
 'Edge case: RCM invoices require a fundamentally different voucher structure',
 'ARCHITECTURE DECISION: Reverse Charge Mechanism (RCM) applies to certain services where the buyer is liable to pay GST directly to the government instead of the supplier collecting it. Common RCM scenarios: legal services, Goods Transport Agency (GTA) services, import of services from overseas. On an RCM invoice, the supplier charges zero GST. But the buyer must post TWO GST entries — an Input GST entry (ITC claim) and an Output GST liability entry (tax payable to government) from the same invoice. This creates a fundamentally different Tally voucher structure compared to regular purchases. RCM invoices cannot be processed through the standard purchase voucher template. Flag RCM invoices separately. Do not attempt to solve the full RCM accounting treatment immediately, but ensure the data model can accommodate it without schema changes.'),

('logic:client_policy:accounting_dna_vision',
 'Client Accounting Policy Engine — the governing brain above all other resolution engines',
 'ARCHITECTURE VISION: Every client has an accounting philosophy — a set of rules that governs every decision the accountant makes. Today these rules exist only in the accountant''s memory. The Client Accounting Policy Engine encodes these rules into the software permanently. This is not a settings page. It is the governing brain that sits above all four resolution engines and determines their behaviour. The hierarchy is: Client Accounting Policy Engine → governs → Supplier Resolution Engine, Item Resolution Engine, Charge Resolution Engine, Tax Ledger Mapping Table. Without this engine, each resolution engine independently asks the accountant questions they have already answered. The Policy Engine eliminates that repeated friction by encoding the answers centrally and applying them automatically.'),

('logic:client_policy:three_layers',
 'Client Accounting DNA has three layers: explicit policy, inferred policy, master data policy',
 'ARCHITECTURE DECISION: The Client Accounting DNA is built from three layers. LAYER 1 — Explicit Policy: answers to the structured onboarding questionnaire. Set by the accountant before the first invoice is processed. Covers ITC policy, inventory behaviour, GST ledger structure, charge treatment, approval preferences. LAYER 2 — Inferred Policy: learned from accountant decisions over time. Every mapping override the accountant makes is recorded. After three consistent overrides of the same type in the same situation, the system asks whether to make it a permanent rule. Never explicitly stated — emerges from behaviour. LAYER 3 — Master Data Policy: inferred from uploaded Tally master exports. Generic vs rate-wise GST ledgers, HSN-based vs product-name item masters, UOM maintained or not. Inferred by analysing the master files, no manual input required. All three layers together form the Client Accounting DNA.'),

('logic:client_policy:governs_all_engines',
 'Client Accounting Policy Engine governs behaviour of all five resolution engines',
 'ARCHITECTURE DECISION: The Client Accounting Policy Engine sets the operating rules for every other engine. Examples: "Client claims ITC" → Tax Ledger Mapping posts to Input CGST/SGST. "Client does NOT claim ITC" → Tax Ledger Mapping absorbs GST into expense/inventory cost. "Client is accounting-oriented" → Item Resolution uses HSN@Rate% matching, never asks for detailed item confirmation. "Client requires supplier review even on GSTIN match" → Supplier Resolution shows popup even at 100% confidence. "Client always books freight separately" → Charge Resolution auto-maps freight without asking. "Client needs new ledger approval" → Charge Resolution always shows popup before creation. The Policy Engine does not resolve anything itself. It sets the rules. The resolution engines execute those rules.'),

('logic:client_policy:questionnaire_scope',
 'Client Accounting Policy Questionnaire — complete scope of questions to eventually cover',
 'ARCHITECTURE DECISION: The onboarding questionnaire must eventually cover the following areas. ITC POLICY: Does this client claim ITC? Any categories where ITC is blocked? How should ineligible ITC be posted? GST LEDGER STRUCTURE: Generic or rate-wise GST ledgers? Which ledger is Input CGST/SGST/IGST? INVENTORY POLICY: Does this client maintain inventory quantities? Maintain UOM? Detailed or HSN-based item master? Does creating new stock item require approval? SUPPLIER POLICY: Should GSTIN-exact-match suppliers auto-map without popup? Do new suppliers require explicit approval? CHARGE POLICY: How is freight treated (separate expense vs absorbed)? Does creating new charge ledger require approval? ROUND-OFF POLICY: What is the round-off ledger name? VOUCHER POLICY: Tally company name, purchase ledger name, default narration format, cost centres used, multiple godowns. APPROVAL POLICY: Does any master creation require senior approval? Should auto-mapping decisions generate notifications?'),

('logic:client_policy:evolution_phases',
 'Client Accounting Policy Engine evolution — four phases from questionnaire to self-completing DNA',
 'ARCHITECTURE VISION: The Client Accounting Policy Engine should evolve through four phases. PHASE 1 — Manual questionnaire at onboarding. Accountant fills it in explicitly. Basic rules are set. PHASE 2 — System learns from decisions. Every time the accountant overrides a suggestion, the system records it as a potential new rule. After three consistent overrides, system asks "Should I always do X in situation Y for this client?" PHASE 3 — Questionnaire becomes self-completing. For new clients, the system analyses their uploaded Tally masters and pre-fills the questionnaire with inferred answers. Accountant reviews and corrects rather than fills from scratch. PHASE 4 — DNA becomes exportable. An accountant who manages a client for years builds up a rich accounting DNA. When handing off to a colleague, they export the DNA. The colleague starts with full institutional knowledge, not from zero.'),

('logic:client_policy:first_class_module',
 'Client Accounting Policy Engine is a first-class foundational module, not a future feature',
 'ARCHITECTURE DECISION: The Client Accounting Policy Engine must be treated as a first-class foundational component of the platform from the very first build, not deferred as a future feature. Reason: every resolution engine makes decisions that depend on client-specific policies. If those policies are not captured from day one, the resolution engines will make wrong decisions and the platform will create bad habits that are difficult to undo. Minimum viable version for day one: a simple questionnaire that captures ITC policy, inventory orientation, and ledger naming convention. This minimum set is enough to prevent the most expensive mistakes. The questionnaire expands incrementally as new resolution engines are built.')

ON CONFLICT (key) DO UPDATE
  SET content     = EXCLUDED.content,
      description = EXCLUDED.description,
      updated_at  = NOW();

